### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by IgorRozani** [MicrosoftDocs/IntuneDocs.pt-br#22]
In the section "[Use markdown para formatar seu tópico](https://github.com/MicrosoftDocs/IntuneDocs.pt-br#use-markdown-para-formatar-seu-t%C3%B3pico)", in the README, has a broken link to a PDF file that doesn't exist in the repository.

![image](https://user-images.githubusercontent.com/802968/47239814-b93e9980-d3bc-11e8-8b9b-f27ec51c6ff3.png)

The link is https://github.com/MicrosoftDocs/IntuneDocs.pt-br/blob/live/contributor-guide/media/documents/markdown-cheatsheet.pdf?raw=true but there isn't a folder contributor-guide or the file markdown-cheatsheet.pdf in the repository.

**Comment by CeciAc** [comment]
Hello, @IgorRozani 

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/IntuneDocs #1585](https://github.com/MicrosoftDocs/IntuneDocs/issues/1585) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @IgorRozani,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/1585.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
